name: pown-proxy
version: '0.0.1'
summary: pown-proxy, a Javascript intercepting proxy
description: |
  pown-proxy is a Javascript intercepting proxy which can be used as standalone
  or as part of the pownjs distribution.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  pown-proxy:
    command: pown-proxy
    plugs: 
      - network

parts:
  pown-proxy:
    source: https://github.com/pownjs/pown-proxy.git
    source-tag: v0.0.1
    plugin: nodejs
    node-engine: 9.4.0

    node-packages: 
      - pown-cli
